feat(tui): add Italian (`it`) locale
fujiapple852/trippy pull request #1355
Opened 2024-10-17 10:13 UTC by fujiapple852

2024-10-17 12:02 UTC, ricott1 requested changes
Some clarifications request. In general, it sounds a bit weird to read these terms in Italian, but I think most are correct :)

2024-10-17 12:02 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Trippy Fallito :("
"Trippy Fallito :(" sounds like trippy failed in life. Here I think you wanna say that it failed executing? Or what is the context exactly?

2024-10-17 12:02 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Fallito"
But here maybe would be nice to know the context as well

2024-10-17 12:20 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "su"
Same for `spento/off`

2024-10-17 13:01 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Perdita%"
```suggestion
  it: "Persi%"
```

2024-10-17 13:02 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Inviare"
```suggestion
  it: "Inviati"
```

This is a bit tricky, I would maybe just leave it in English

2024-10-17 13:02 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Ricevere"
```suggestion
  it: "Ricevuti"
```

Here as well, I would maybe just leave it in English

2024-10-17 13:03 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "StDev"
In theory this would be translated as `Deviazione standard`, but I think it's better to leave it in english

2024-10-17 13:58 UTC, fujiapple852 commented on crates/trippy-tui/locales/app.yml
> +  it: "su"
If `on` is more natural then i'll update it to use that.

2024-10-17 14:05 UTC, fujiapple852 commented on crates/trippy-tui/locales/app.yml
> +  it: "Fallito"
This is the name of the column which shows the number of probe failures.  Here is what it looks like:

<img width="848" alt="Screenshot 2024-10-17 at 10 04 44 PM" src="https://github.com/user-attachments/assets/fbd72e7b-638b-4492-a1a3-43513226c573">

For the column names screen space is at a premium so short names or abbreviations are preferred.

2024-10-17 16:03 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Fallito"
Anyway, I would use the plural form "Falliti"

2024-10-17 16:04 UTC, fujiapple852 commented on crates/trippy-tui/locales/app.yml
> +  it: "Fallito"
Press 7 to go to the column settings, scroll down to the bottom and press c on the column to enable it.

2024-10-17 16:05 UTC, ricott1 commented on crates/trippy-tui/locales/app.yml
> +  it: "Trippy Fallito :("
Ok, this is a bit funny, but in Italian I would either use "Trippy e' crashato" which is basically the italianization of "crashed" or something like "Trippy ha avuto un problema" ("Trippy encountered a problem")

2024-10-18 14:11 UTC, fujiapple852 commented
All changes made @ricott1 and this is ready to merge, thanks again!

2024-10-18 14:39 UTC, merged